# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Tank\00719_grandpa\dev\install\apps\tk-multi-renderfarm\resources/dialog.ui'
#
# Created: Mon Nov 11 17:58:44 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(797, 446)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.items_title_label = QtGui.QLabel(Dialog)
        self.items_title_label.setStyleSheet("#items_title_label {\n"
"font-size: 14px\n"
"}")
        self.items_title_label.setIndent(4)
        self.items_title_label.setObjectName("items_title_label")
        self.verticalLayout_7.addWidget(self.items_title_label)
        self.renders_stacked_widget = QtGui.QStackedWidget(Dialog)
        self.renders_stacked_widget.setStyleSheet("")
        self.renders_stacked_widget.setObjectName("renders_stacked_widget")
        self.renders_page = QtGui.QWidget()
        self.renders_page.setObjectName("renders_page")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.renders_page)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.task_scroll = QtGui.QScrollArea(self.renders_page)
        self.task_scroll.setStyleSheet("#task_scroll {\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(32,32,32);\n"
"}")
        self.task_scroll.setWidgetResizable(True)
        self.task_scroll.setObjectName("task_scroll")
        self.contents = QtGui.QWidget()
        self.contents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.contents.setObjectName("contents")
        self.task_scroll.setWidget(self.contents)
        self.horizontalLayout_7.addWidget(self.task_scroll)
        self.renders_stacked_widget.addWidget(self.renders_page)
        self.no_renders_page = QtGui.QWidget()
        self.no_renders_page.setStyleSheet("")
        self.no_renders_page.setObjectName("no_renders_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.no_renders_page)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.no_renders_frame = QtGui.QFrame(self.no_renders_page)
        self.no_renders_frame.setStyleSheet("#no_publishes_frame {\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(32,32,32);\n"
"}")
        self.no_renders_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.no_renders_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.no_renders_frame.setObjectName("no_renders_frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.no_renders_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtGui.QSpacerItem(0, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(self.no_renders_frame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtGui.QSpacerItem(0, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.no_renders_frame)
        self.renders_stacked_widget.addWidget(self.no_renders_page)
        self.verticalLayout_7.addWidget(self.renders_stacked_widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_title_label = QtGui.QLabel(Dialog)
        self.info_title_label.setStyleSheet("#info_title_label {\n"
"font-size: 14px\n"
"}")
        self.info_title_label.setIndent(4)
        self.info_title_label.setObjectName("info_title_label")
        self.verticalLayout.addWidget(self.info_title_label)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.priority_spinBox = QtGui.QSpinBox(self.groupBox)
        self.priority_spinBox.setMaximumSize(QtCore.QSize(45, 9999))
        self.priority_spinBox.setProperty("value", 0)
        self.priority_spinBox.setObjectName("priority_spinBox")
        self.gridLayout.addWidget(self.priority_spinBox, 1, 2, 1, 1)
        self.start_spinBox = QtGui.QSpinBox(self.groupBox)
        self.start_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.start_spinBox.setMinimum(-9999999)
        self.start_spinBox.setMaximum(99999999)
        self.start_spinBox.setObjectName("start_spinBox")
        self.gridLayout.addWidget(self.start_spinBox, 2, 2, 1, 1)
        self.end_spinBox = QtGui.QSpinBox(self.groupBox)
        self.end_spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.end_spinBox.setMinimum(-9999999)
        self.end_spinBox.setMaximum(99999999)
        self.end_spinBox.setObjectName("end_spinBox")
        self.gridLayout.addWidget(self.end_spinBox, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.limit_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.limit_lineEdit.setObjectName("limit_lineEdit")
        self.gridLayout.addWidget(self.limit_lineEdit, 4, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.jobname_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.jobname_lineEdit.setObjectName("jobname_lineEdit")
        self.gridLayout.addWidget(self.jobname_lineEdit, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.cancel_btn = QtGui.QPushButton(Dialog)
        self.cancel_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.submit_btn = QtGui.QPushButton(Dialog)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout.addWidget(self.submit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.renders_stacked_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Tank Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.items_title_label.setText(QtGui.QApplication.translate("Dialog", "Choose Items to Submit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic;\">This render does not have any optional items to choose from.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.info_title_label.setText(QtGui.QApplication.translate("Dialog", "Edit Information about your Submission:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Limits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Jobname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.submit_btn.setText(QtGui.QApplication.translate("Dialog", "Submit", None, QtGui.QApplication.UnicodeUTF8))

